### ISSUE TITLE
Limit sniffing on broadcasts

### ISSUE THREAD

**Issue by commonsguy** [jgilfelt/GhostLog#2]
Right now, AFAICT, anyone can listen in on broadcasts from an integration-enabled app to GhostLog and therefore sniff on log messages. In theory, that should not happen in production, as nobody should ship an app with GhostLog integration enabled.

In theory, I'd have hair. :-)

Three ways come to mind to help limit this:
1. Have the `Intent` for the broadcast specify the component name, instead of (or in addition to) the action string. This will limit your ability to refactor this portion of GhostLog, so as not to break prior integration code, but it would preclude other apps from receiving the broadcast. However, this would require you to move your `BroadcastReceiver` into your manifest, as opposed to the `registerReceiver()` that you have today.
2. Use an `IntentFilter` that sets the priority to `Integer.MAX_VALUE` and use an ordered broadcast, aborting it after you receive it. This means that a potential sniffer would have to set up their receiver first. However, again, I think your use of `registerReceiver()` may be a problem here -- while I have not tried playing with competing apps, one registered in the manifest, one registered via `registerReceiver()`, I would not be the least bit surprised if the manifest one gets in first, at least in certain circumstances.
3. Use a custom permission that integration-enabled apps must request via `<uses-permission>`. This would at least alert users to other apps that want to listen in on GhostLog broadcasts. Alas, you cannot use `signature`-level permissions, since the integration-enabled apps aren't written by you, in general.

**Comment by jgilfelt** [comment]
Thanks! I'm definitely not tied to the `registerReceiver()` approach as I had it declared in the manifest yesterday prior to one last refactoring.

**Comment by hvisser** [comment]
I think the permission would be the best option, and it should also be applied to the broadcast that sends the signal to enable logging in the target app(s) so that only GhostLog can enable the logging process.

**Comment by jgilfelt** [comment]
It looks like I might have to go with permission protection alone. Moving the receiver into the manifest seems to mean the instance can only really talk to my service via `context.startService()` which is incurring a big performance overhead. Event bus implementations were similarly slow and thus removed.

I will also update the docs to recommend using the dependency via Gradle's `debugCompile` directive, which may further mitigate inadvertent production integrations (for Gradle users at least).
