### ISSUE TITLE
Gradle version doesn't actually work (non-root)

### ISSUE THREAD

**Issue by mbarany** [jgilfelt/GhostLog#5]
1) I installed the app from the PlayStore
2) Added `compile 'com.readystatesoftware.ghostlog:ghostlog-integration:+'` to build.gradle
3) Turn it on, but it doesn't work.

I can confirm the JAR + manifest code works.

Am I doing something wrong?
Thoughts?

Thanks!

**Comment by jgilfelt** [comment]
Oops looks like I messed up here - if you append `@aar` to the compile target, then re-sync your project with gradle files and do a clean build it should work:

`debugCompile 'com.readystatesoftware.ghostlog:ghostlog-integration:+@aar'`

It seems like the JAR file takes precedence over AAR if you distribute both via Maven central.

Let me know if that works.

**Comment by mbarany** [comment]
So I am able to now pull in the aar, but I get this manifest merge error:
`Main manifest has <uses-sdk android:minSdkVersion='10'> but library uses minSdkVersion='14'`

I've tested with minSdk of 8 and seems to work.

**Comment by jgilfelt** [comment]
Thanks - I've merged your PR and deployed a new version of the artefact. It will take about 2 hours to sync with maven central. Sorry for the screw up, I'm still figuring out this Gradle stuff.

**Comment by mbarany** [comment]
thanks. I'll try it when it becomes available.
no worries, this is a really cool logcat!

**Comment by mbarany** [comment]
It's working now in 1.0.2
thanks!
